repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        files: '^src/'
    -   id: end-of-file-fixer
        files: '^src/'
    -   id: trailing-whitespace
        files: '^src/'
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.252'
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        files: '^src/'
-   repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        files: '^src/'
        args: ["--profile", "black"]
-   repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        args: ["--config=./.flake8"]
        additional_dependencies:
          - flake8-bugbear==22.9.23
          - flake8-comprehensions==3.10.0
          - flake8-simplify==0.19.3
