name: Build Poetry Image
run-name: ${{github.actor}} is conducting a build of poetry
on:
  workflow_dispatch:
#  push:
#    branches: [main]
#    paths:
#      - 'tools/poetry.Dockerfile'
env:
  REGISTRY: ghcr.io
  POETRY_IMAGE_NAME: poetry
  POETRY_VERSION: poetry
defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
    outputs:
      poetry_version: ${{ steps.env_var.outputs.POETRY_VERSION }}
      pytest_version: ${{ steps.env_var.outputs.PYTEST_VERSION }}

    steps:
      - uses: actions/checkout@v3

      - id: env_var
        name: Set Versions for Poetry and Pytest
        run: |
          POETRY_VERSION=$(make poetry_version)
          echo "POETRY_VERSION=$POETRY_VERSION" >> $GITHUB_OUTPUT
          PYTEST_VERSION=$(make pytest_version)
          echo "PYTEST_VERSION=$PYTEST_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.POETRY_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./tools/poetry.Docker
          push: true
          build-args: |
            POETRY_VERSION=${{ needs.build.outputs.poetry_version}}
            PYTEST_VERSION=${{ needs.build.outputs.pytest_version}}
          tags: ${{ needs.build.outputs.poetry_version}}
