name: Build
run-name: ${{github.actor}} is conducting a build of maas-ctl
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags: ["v**"]
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS ECR Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          role-session-name: maasctl-ecr
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build poetry image
        run: |
          make _build_poetry

      - name: Build wheel file
        run: |
          make build

      - name: Build container image
        run: |
          make build_image

      - name: Push container image
        run: |
          make push_image