name: Lint, Format and Test
run-name: ${{github.actor}} is conducting code quality checks for maas-ctl
on:
  pull_request:
    types: [opened, synchronize]
defaults:
  run:
    shell: bash

jobs:

  build:
    name: Install, build, lint
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          make install

      - name: Build wheel file
        run: |
          make build

      - name: Lint and Format
        run: |
          make lint
          make format
