name: Lint, Format and Test
run-name: ${{github.actor}} is conducting code quality checks for maas-ctl
on:
  pull_request:
    types: [opened, synchronize]
defaults:
  run:
    shell: bash

jobs:

  build:
    name: Install, build, lint
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build poetry image
        run: |
          make build_poetry

      - name: Install dependencies
        run: |
          make install

      - name: Build wheel file
        run: |
          make build

      - name: Lint and Format
        run: |
          make lint
          make format
